##############################################################################
## Pre-processing config file for pilot dataset
##############################################################################

##############################################################################
## THREADING
##############################################################################

# ----------------------------------------------------------------------------
# Number of threads to use for large, medium, and small multithreaded jobs; 
#       if number passed to job is larger than number passed to whole
#       workflow, latter will be used instead.
# ----------------------------------------------------------------------------

threads:
    max: 36 # Max threads for very large jobs
    mor: 18 # Max threads for large jobs
    med: 9 # Threads for medium jobs
    min: 4 # Min threads for small (but still multithreaded) jobs

##############################################################################
## PATH TO WORKFLOW BASE SNAKEFILE
##############################################################################

base_path_preprocess: "/beegfs/group_dv/home/WBradshaw/workflows_source/igseq/killifish-igseq/preprocessing/source/snakefiles/base"

##############################################################################
## SAMPLE INFO
##############################################################################

# ----------------------------------------------------------------------------
# UNIVERSAL SAMPLE INFO
# ----------------------------------------------------------------------------
# Key/value classification pairs applying across all samples.
# You can add any extra keys and arbitrary values you want here.
# ----------------------------------------------------------------------------

info_all:
    SEX: M
    STRAIN: GRZ-AD
    DEATH_DATE: "2016-07-04"
    RUN: 1
    AGE_DAYS: 56


# ----------------------------------------------------------------------------
# RAW READS FILES (`reads` key)
# ----------------------------------------------------------------------------
# Specify input paths for paired IgSeq reads files
# dir = parent directory for reads files
# 5prime = reads at 5' end of molecule, containing TSA, UMI and V-segment
# 3prime = reads at 3' end of molecule, containing CM1 primer
# ----------------------------------------------------------------------------
# SAMPLE CLASSIFICATION INFO (`info` key)
# ----------------------------------------------------------------------------
# Key/value pairs specifying how to classify this sample.
# You can add any extra keys and arbitrary values you want here, EXCEPT for
#     REPLICATE and INDIVIDUAL, which are reserved.
# Used for sample grouping during downstream analysis.
# ----------------------------------------------------------------------------

# NB: No underscores in sample names!
# 2-3-bio
samples:
    2-3-bio:
        reads:
            dir: reads/2-3-bio
            3prime: 2-3-bio_S3_L001_R1_001.fastq
            5prime: 2-3-bio_S3_L001_R2_001.fastq
        info:
            FISH: 2-03
            REP: bio
            ID: grz-AD_4152_E
            WEIGHT: 1.33
            AGE_REP: 56-bio
    2-4-bio:
        reads:
            dir: reads/2-4-bio
            3prime: 2-4-bio_S6_L001_R1_001.fastq 
            5prime: 2-4-bio_S6_L001_R2_001.fastq
        info:
            FISH: 2-04
            REP: bio
            ID: grz-AD_4132_E
            WEIGHT: 1.35
            AGE_REP: 56-bio
    2-5-bio:
        reads:
            dir: reads/2-5-bio
            3prime: 2-5-bio_S9_L001_R1_001.fastq
            5prime: 2-5-bio_S9_L001_R2_001.fastq
        info:
            FISH: 2-05
            REP: bio
            ID: grz-AD_4177_E
            WEIGHT: 1.22
            AGE_REP: 56-bio
    2-6-bio:
        reads:
            dir: reads/2-6-bio
            3prime: 2-6-bio_S12_L001_R1_001.fastq
            5prime: 2-6-bio_S12_L001_R2_001.fastq
        info:
            FISH: 2-06
            REP: bio
            ID: grz-AD_4158_E
            WEIGHT: 1.51
            AGE_REP: 56-bio
    2-3-lib:
        reads:
            dir: reads/2-3-lib
            3prime: 2-3-lib_S2_L001_R1_001.fastq
            5prime: 2-3-lib_S2_L001_R2_001.fastq
        info:
            FISH: 2-03
            REP: lib
            ID: grz-AD_4152_E
            WEIGHT: 1.33
            AGE_REP: 56-lib
    2-4-lib:
        reads:
            dir: reads/2-4-lib
            3prime: 2-4-lib_S5_L001_R1_001.fastq
            5prime: 2-4-lib_S5_L001_R2_001.fastq
        info:
            FISH: 2-04
            REP: lib
            ID: grz-AD_4132_E
            WEIGHT: 1.35
            AGE_REP: 56-lib
    2-5-lib:
        reads:
            dir: reads/2-5-lib
            3prime: 2-5-lib_S8_L001_R1_001.fastq
            5prime: 2-5-lib_S8_L001_R2_001.fastq
        info:
            FISH: 2-05
            REP: lib
            ID: grz-AD_4177_E
            WEIGHT: 1.22
            AGE_REP: 56-lib
    2-6-lib:
        reads:
            dir: reads/2-6-lib
            3prime: 2-6-lib_S11_L001_R1_001.fastq
            5prime: 2-6-lib_S11_L001_R2_001.fastq
        info:
            FISH: 2-06
            REP: lib
            ID: grz-AD_4158_E
            WEIGHT: 1.51
            AGE_REP: 56-lib
    2-3-orig:
        reads:
            dir: reads/2-3-orig
            3prime: 2-3-orig_S1_L001_R1_001.fastq
            5prime: 2-3-orig_S1_L001_R2_001.fastq
        info:
            FISH: 2-03
            REP: orig
            ID: grz-AD_4152_E
            WEIGHT: 1.33
            AGE_REP: 56-orig
    2-4-orig:
        reads:
            dir: reads/2-4-orig
            3prime: 2-4-orig_S4_L001_R1_001.fastq
            5prime: 2-4-orig_S4_L001_R2_001.fastq
        info:
            FISH: 2-04
            REP: orig
            ID: grz-AD_4132_E
            WEIGHT: 1.35
            AGE_REP: 56-orig
    2-5-orig:
        reads:
            dir: reads/2-5-orig
            3prime: 2-5-orig_S7_L001_R1_001.fastq
            5prime: 2-5-orig_S7_L001_R2_001.fastq
        info:
            FISH: 2-05
            REP: orig
            ID: grz-AD_4177_E
            WEIGHT: 1.22
            AGE_REP: 56-orig
    2-6-orig:
        reads:
            dir: reads/2-6-orig
            3prime: 2-6-orig_S10_L001_R1_001.fastq
            5prime: 2-6-orig_S10_L001_R2_001.fastq
        info:
            FISH: 2-06
            REP: orig
            ID: grz-AD_4158_E
            WEIGHT: 1.51
            AGE_REP: 56-orig

# Key(s) to split aggregate data on during pRESTO pre-processing
# (e.g. to collapse sequencing replicates)
info_key_replicate: "FISH REP"
# Key(s) to split aggregate data on to obtain biological individuals
# (e.g. for clonotyping)
info_key_individual: "FISH"
# Key(s) to aggregate on for read counting (generally SAMPLE, REPLICATE, or
# INDIVIDUAL)
count_on: "REPLICATE"

##############################################################################
## REFERENCE FILES
##############################################################################

# ----------------------------------------------------------------------------
# GERMLINE DATABASES
# ----------------------------------------------------------------------------
# Specify input paths for IGH V, D, J and C-sequences from reference database
# ----------------------------------------------------------------------------

germline_segments:
    v: source/source/input_files/vdj/vh_imgt.fasta
    d: source/source/input_files/vdj/dh.fasta
    j: source/source/input_files/vdj/jh.fasta

# ----------------------------------------------------------------------------
# AUXILIARY FILE
# ----------------------------------------------------------------------------
# Specify input path for J-auxiliary file (for IgBLAST alignment)
# ----------------------------------------------------------------------------

auxiliary_file: source/source/input_files/vdj/jh_aux.txt

# ----------------------------------------------------------------------------
# PRIMERS AND OLIGOS
# ----------------------------------------------------------------------------
# Specify input path for TSA sequence file and 5'/3' primer sequences
# ----------------------------------------------------------------------------

primers:
    c: source/source/input_files/oligos/cprimers.fasta
    tsa: source/source/input_files/oligos/m1s.fasta

tsa: source/source/input_files/oligos/tsa.fasta

##############################################################################
## PRESTO CONFIGURATION
##############################################################################

# ----------------------------------------------------------------------------
# PRESTO PRE-PROCESSING PARAMETERS
# ----------------------------------------------------------------------------
# filter_qual: Quality threshold for read filtering
# tsa_barcode_length: Distance from end of fixed TSA primer sequence to end
#       of UMI (counting from 0)
# tsa_max_error: Maximum error tolerance for UMI extraction during primer
#       masking (high = tolerant; high by default)
# pairseq_coord: Co-ordinate system for barcode unification; use "illumina"
#       for raw sequencing data, "SRA" for SRA-downloaded data
# build_consensus_max_error: Maximum error tolerance for MIG clustering
#       (high = tolerant; low by default)
# build_consensus_max_gap: Maximum gap *rate* for MIG clustering
#       (high = tolerant)
# collapse_seq_max_gap: Maximum gap *number* for sequence collapse
#       (high = tolerant)
# ----------------------------------------------------------------------------
# TODO: Add params for primer start co-ordinates?

presto_params:
    filter_qual: 20 
    tsa_barcode_length: 16
    tsa_max_error: 0.5
    cluster_umis: True
    cluster_barcodes_pident: 0.9 # TODO: Test this
    cluster_sets_pident: 0.75 # TODO: Test this
    pairseq_coord: "illumina"
    build_consensus_max_error: 0.1 
    build_consensus_max_gap: 0.5 
    collapse_seq_max_gap: 20 

presto_log_fields:
    filter_seq: ID QUALITY #SEQ
    mask_primers: ID PRIMER ERROR #SEQORIENT PRORIENT PRSTART INSEQ ALIGN OUTSEQ
    cluster_sets: ID BARCODE SEQCOUNT CLUSTERS
    mask_barcodes: ID PRIMER BARCODE ERROR #SEQORIENT PRORIENT PRSTART INSEQ ALIGN OUTSEQ
    build_consensus: BARCODE SEQCOUNT CONSCOUNT ERROR # ID PRIMER PRCOUNT PRCONS PRFREQ CONSENSUS QUALITY
    assemble_pairs: ID LENGTH OVERLAP ERROR PVALUE # FIELDS1 FIELDS2 SEQ1 SEQ2 ASSEMBLY QUALITY
    split_seq: ID CONSCOUNT DUPCOUNT

##############################################################################
## CHANGE-O CONFIGURATION
##############################################################################

# ----------------------------------------------------------------------------
# SHAZAM NEAREST-NEIGHBOUR PARAMETERS
# ----------------------------------------------------------------------------
# Parameters to pass to DistToNearest for computing nearest-neighbours
#
# model: Distance model to use ("ham" = nucleotide Hamming distance,
#       "aa" = amino-acid Hamming distance)
# symmetry: Method for combining A -> B and B -> A distances
#       ("min" = minimum, "avg" = average)
# normalize: Normalisation method ("len" = by sequence length, 
#       "none" = no normalisation)
# ----------------------------------------------------------------------------

dist_to_nearest:
    model: "ham"
    symmetry: "min"
    normalize: "len"

# ----------------------------------------------------------------------------
# SHAZAM DISTANCE THRESHOLD PARAMETERS
# ----------------------------------------------------------------------------
# Parameters to pass to findThreshold for threshold inference for clonotyping
#
# method: Statistical method to use ("gmm": maximum-likelihood-model-based,
#       "density": kernel-density-based)
# model: Statistical distributions to fit to upper and lower curves
#       ("norm-norm", "gamma-gamma", "gamma-norm" or "norm-gamma")
# cutoff: Method for identifying threshold from fitted curves
#       ("opt" = optimum sensitivity/specificity threshold,
#       "intersect" = intersection of the two curves)
# NB: model and cutoff only affect the result in gmm mode, not density mode
# ----------------------------------------------------------------------------

infer_cluster_threshold:
    cutoff: "opt"
