##############################################################################
## Example config file for Ig-Seq downstream-analysis pipeline
## Copy to intended workflow directory and update prior to running
##############################################################################

##############################################################################
## THREADING
##############################################################################

# ----------------------------------------------------------------------------
# Number of threads to use for large, medium, and small multithreaded jobs; 
#       if number passed to job is larger than number passed to whole
#       workflow, latter will be used instead.
# ----------------------------------------------------------------------------

threads:
    max: 18 # Max threads for large jobs
    med: 9 # Threads for medium jobs
    min: 4 # Min threads for small (but still multithreaded) jobs

##############################################################################
## PATH TO WORKFLOW BASE SNAKEFILE
##############################################################################

base_path_preprocess: "path_to_source_dir"
    # Path to directory containing workflow source code (i.e. this directory)

##############################################################################
## PATHS TO PRE-PROCESSED DATA
##############################################################################

out_dir_changeo: "path_to_changeo_output"
    # Path to directory containing Change-O output from preprocessing pipeline

##############################################################################
## GROUP FILTERING SETTINGS
##############################################################################

filter_groups:
    INDIVIDUAL:
        - test1
    AGE_DAYS: 
        - 128

keep_complement: True 
# If True, discard groups in filter_groups and keep the rest. If False,
# keep groups in filter_groups and discard the rest.

##############################################################################
## DIVERSITY SPECTRUM COMPUTATION
##############################################################################

# ----------------------------------------------------------------------------
# CLONE-SIZE DIVERSITY SPECTRUM PARAMETERS
# ----------------------------------------------------------------------------
# min_q, max_q, step_q: Minimum, maximum and step size for diversity orders
#       to calculate
# min_n, max_n: Minimum/maximum number of observations to sample. A group with 
#       fewer observations than the min / more than the max is excluded.
# ----------------------------------------------------------------------------

clone_div_parameters:
    min_q: 0
    max_q: 4
    step_q: 0.05
    min_n: 30
    max_n: None
    nboot: 2000

# ----------------------------------------------------------------------------
# SEGMENT DIVERSITY SPECTRUM PARAMETERS
# ----------------------------------------------------------------------------
# Same parameters as above, but for computing the V/D/J-usage diversity.
# ----------------------------------------------------------------------------

vdj_div_parameters:
    min_q: 0
    max_q: 4
    step_q: 0.05
    min_n: 30
    max_n: None
    nboot: 2000

##############################################################################
## IGOR PARAMETERS
##############################################################################

igor_default_model: ""

# Which individuals to analyse (separately) with IGoR?
igor_individuals:
    - "test"

igor_group_by: "AGE_DAYS"
igor_groups:
    - "39"

# Paths to V/D/J databases, WITHOUT IMGT-gapping

segment_paths:
    V: "input_files/vdj/v_no_imgt.fasta"
    V_IMGT: "input_files/vdj/v.fasta"
    D: "input_files/vdj/d_no_imgt.fasta"
    J: "input_files/vdj/j_no_imgt.fasta"

j_aux_file: "input_files/vdj/j.aux"
