##############################################################################
## SNAKEFILE
## PIPELINE: Immunoglobulin sequencing analysis
## SUB-PIPELINE: Downstream analysis
## FILE: Snakefile
## AUTHOR: Will Bradshaw
##############################################################################
## Example run snakefile for Ig-Seq downstream-analysis pipeline
##############################################################################

out_dir = "outfiles"
log_dir = "logs"

configfile: "config_analysis.yaml"
include: config["base_path_analysis"]

#------------------------------------------------------------------------------
# Default rule
#------------------------------------------------------------------------------

rule all:
    input:
        expand("outfiles/analysis/presto/count/" + \
            "{sample}_400000_0_report_parse-add.tab",\
            sample = list(config["samples"]))
