##############################################################################
## Example config file for Ig-Seq pre-processing pipeline
## Copy to intended workflow directory and update prior to running
##############################################################################

##############################################################################
## THREADING
##############################################################################

# ----------------------------------------------------------------------------
# Number of threads to use for large, medium, and small multithreaded jobs; 
#       if number passed to job is larger than number passed to whole
#       workflow, latter will be used instead.
# ----------------------------------------------------------------------------

threads:
    max: 36 # Max threads for very large jobs
    mor: 18 # Max threads for large jobs
    med: 9 # Threads for medium jobs
    min: 4 # Min threads for small (but still multithreaded) jobs

##############################################################################
## PATH TO WORKFLOW BASE SNAKEFILE
##############################################################################

base_path_preprocess: "path_to_source_dir"
    # Path to directory containing workflow source code (i.e. this directory)

##############################################################################
## SAMPLE INFO
##############################################################################

# ----------------------------------------------------------------------------
# UNIVERSAL SAMPLE INFO
# ----------------------------------------------------------------------------
# Key/value classification pairs applying across all samples.
# You can add any extra keys and arbitrary values you want here.
# ----------------------------------------------------------------------------

info_all:
    SEX: M
    STRAIN: GRZ-AD
    DEATH_DATE: "2016-07-04"
    RUN: 1
    AGE_DAYS: 56

# ----------------------------------------------------------------------------
# RAW READS FILES (`reads` key)
# ----------------------------------------------------------------------------
# Specify input paths for paired IgSeq reads files
# dir = parent directory for reads files
# 5prime = reads at 5' end of molecule, containing TSA, UMI and V-segment
# 3prime = reads at 3' end of molecule, containing CM1 primer
# ----------------------------------------------------------------------------
# SAMPLE CLASSIFICATION INFO (`info` key)
# ----------------------------------------------------------------------------
# Key/value pairs specifying how to classify this sample.
# You can add any extra keys and arbitrary values you want here, EXCEPT for
#     REPLICATE and INDIVIDUAL, which are reserved.
# Used for sample grouping during downstream analysis.
# ----------------------------------------------------------------------------

samples:
    2-3-bio:
        reads:
            dir: infiles/reads/2-3-bio
            3prime: 2-3-bio_S3_L001_R1_001.fastq
            5prime: 2-3-bio_S3_L001_R2_001.fastq
        info:
            FISH: 2-03
            REP: bio
            ID: grz-AD_4152_E
            WEIGHT: 1.33
            AGE_REP: 56-bio

# Key(s) to split aggregate data on during pRESTO pre-processing
# (e.g. to collapse sequencing replicates)
info_key_replicate: "FISH REP"
# Key(s) to split aggregate data on to obtain biological individuals
# (e.g. for clonotyping)
info_key_individual: "FISH"
# Key(s) to aggregate on for read counting (generally SAMPLE, REPLICATE, or
# INDIVIDUAL)
count_on: "REPLICATE"

##############################################################################
## REFERENCE FILES
##############################################################################

# ----------------------------------------------------------------------------
# GERMLINE DATABASES
# ----------------------------------------------------------------------------
# Specify input paths for IGH V, D, J and C-sequences from reference database
# ----------------------------------------------------------------------------

germline_segments:
    v: infiles/vdj/vh_imgt_renamed.fasta
    d: infiles/vdj/dh_renamed.fasta
    j: infiles/vdj/jh_renamed.fasta

# ----------------------------------------------------------------------------
# AUXILIARY FILE
# ----------------------------------------------------------------------------
# Specify input path for J-auxiliary file (for IgBLAST alignment)
# ----------------------------------------------------------------------------

auxiliary_file: infiles/vdj/jh_aux_renamed.txt

# ----------------------------------------------------------------------------
# PRIMERS AND OLIGOS
# ----------------------------------------------------------------------------
# Specify input path for TSA sequence file and 5'/3' primer sequences
# ----------------------------------------------------------------------------

primers:
    c: infiles/oligos/cprimers.fasta
    tsa: infiles/oligos/m1s.fasta

tsa: infiles/oligos/tsa.fasta

##############################################################################
## PRESTO CONFIGURATION
##############################################################################

# ----------------------------------------------------------------------------
# PRESTO PRE-PROCESSING PARAMETERS
# ----------------------------------------------------------------------------
# filter_qual: Quality threshold for read filtering
# tsa_barcode_length: Distance from end of fixed TSA primer sequence to end
#       of UMI (counting from 0)
# tsa_max_error: Maximum error tolerance for UMI extraction during primer
#       masking (high = tolerant; high by default)
# pairseq_coord: Co-ordinate system for barcode unification; use "illumina"
#       for raw sequencing data, "SRA" for SRA-downloaded data
# build_consensus_max_error: Maximum error tolerance for MIG clustering
#       (high = tolerant; low by default)
# build_consensus_max_gap: Maximum gap *rate* for MIG clustering
#       (high = tolerant)
# collapse_seq_max_gap: Maximum gap *number* for sequence collapse
#       (high = tolerant)
# ----------------------------------------------------------------------------

presto_params:
    filter_qual: 20 
    tsa_barcode_length: 16
    tsa_max_error: 0.5
    cluster_umis: True
    cluster_barcodes_pident: 0.9
    cluster_sets_pident: 0.75
    pairseq_coord: "illumina"
    build_consensus_max_error: 0.1
    build_consensus_max_gap: 0.5
    collapse_seq_max_gap: 20

presto_log_fields:
    filter_seq: ID QUALITY #SEQ
    mask_primers: ID PRIMER ERROR #SEQORIENT PRORIENT PRSTART INSEQ ALIGN OUTSEQ
    cluster_sets: ID BARCODE SEQCOUNT CLUSTERS
    mask_barcodes: ID PRIMER BARCODE ERROR #SEQORIENT PRORIENT PRSTART INSEQ ALIGN OUTSEQ
    build_consensus: BARCODE SEQCOUNT CONSCOUNT ERROR # ID PRIMER PRCOUNT PRCONS PRFREQ CONSENSUS QUALITY
    assemble_pairs: ID LENGTH OVERLAP ERROR PVALUE # FIELDS1 FIELDS2 SEQ1 SEQ2 ASSEMBLY QUALITY
    split_seq: ID CONSCOUNT DUPCOUNT

##############################################################################
## CHANGE-O CONFIGURATION
##############################################################################

# ----------------------------------------------------------------------------
# SHAZAM NEAREST-NEIGHBOUR PARAMETERS
# ----------------------------------------------------------------------------
# Parameters to pass to DistToNearest for computing nearest-neighbours
#
# model: Distance model to use ("ham" = nucleotide Hamming distance,
#       "aa" = amino-acid Hamming distance)
# symmetry: Method for combining A -> B and B -> A distances
#       ("min" = minimum, "avg" = average)
# normalize: Normalisation method ("len" = by sequence length, 
#       "none" = no normalisation)
# ----------------------------------------------------------------------------

dist_to_nearest:
    model: "ham"
    symmetry: "min"
    normalize: "len"

# ----------------------------------------------------------------------------
# SHAZAM DISTANCE THRESHOLD PARAMETERS
# ----------------------------------------------------------------------------
# Parameters to pass to findThreshold for threshold inference for clonotyping
#
# method: Statistical method to use ("gmm": maximum-likelihood-model-based,
#       "density": kernel-density-based)
# model: Statistical distributions to fit to upper and lower curves
#       ("norm-norm", "gamma-gamma", "gamma-norm" or "norm-gamma")
# cutoff: Method for identifying threshold from fitted curves
#       ("opt" = optimum sensitivity/specificity threshold,
#       "intersect" = intersection of the two curves)
# NB: model and cutoff only affect the result in gmm mode, not density mode
# ----------------------------------------------------------------------------

infer_cluster_threshold:
    cutoff: "opt"
