##############################################################################
## Example run snakefile for Ig-Seq pipeline
## Copy to intended workflow directory and update prior to running
##############################################################################

out_dir = "output_files"
log_dir = "log_files"

configfile: "config_preprocess.yaml" # Path to config file
include: config["base_path_preprocess"]

#------------------------------------------------------------------------------
# Default rule
#------------------------------------------------------------------------------

rule all:
    input:
        # pRESTO output files
        "output_files/presto/output/R12_merged_atleast-2.fasta",
        "output_files/presto/count/report.tsv",
        # IgBLAST output file
        "output_files/igblast/igblast_merged.fmt7",
        # Change-O output files
        "output_files/changeo/output/seqs-all.tab",
        "output_files/changeo/output/seqs-functional.tab",
        "output_files/changeo/output/seqs-nonfunctional.tab",
        "output_files/changeo/count/report.tsv",
        # Collated read survival
        "output_files/changeo/count/reports-combined.tsv",
